// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriorAuthorization.Shared.Data;

#nullable disable

namespace PriorAuthorization.Shared.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620102306_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.AuditHistory", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("audit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<byte>("ActionType")
                        .HasColumnType("tinyint")
                        .HasColumnName("action_type");

                    b.Property<int?>("AuthId")
                        .HasColumnType("int")
                        .HasColumnName("auth_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int")
                        .HasColumnName("encounter_id");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("NewValue")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("old_value");

                    b.Property<byte>("PerformedByRole")
                        .HasColumnType("tinyint")
                        .HasColumnName("performed_by_role");

                    b.Property<string>("Remarks")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("remarks");

                    b.HasKey("AuditId")
                        .HasName("PK__AuditHis__5AF33E33C9BD28E5");

                    b.HasIndex("AuthId");

                    b.HasIndex("EncounterId");

                    b.ToTable("AuditHistory");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.AuthorizationRequest", b =>
                {
                    b.Property<int>("AuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auth_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthId"));

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("approved_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("EncounterId")
                        .HasColumnType("int")
                        .HasColumnName("encounter_id");

                    b.Property<decimal>("EstimatedTotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("estimated_total_amount");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<int>("PayerId")
                        .HasColumnType("int")
                        .HasColumnName("payer_id");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("reviewed_at");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("AuthId")
                        .HasName("PK__Authoriz__6531B6F5BD59FE4D");

                    b.HasIndex("PayerId");

                    b.HasIndex(new[] { "EncounterId" }, "UQ__Authoriz__CDF1340ED8DB83D1")
                        .IsUnique();

                    b.ToTable("AuthorizationRequest");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.AuthorizationService", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("AuthId")
                        .HasColumnType("int")
                        .HasColumnName("auth_id");

                    b.Property<string>("CptCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cpt_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("estimated_cost");

                    b.Property<string>("IcdCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("icd_code");

                    b.Property<string>("Notes")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("notes");

                    b.HasKey("ServiceId")
                        .HasName("PK__Authoriz__3E0DB8AF05E40307");

                    b.HasIndex("AuthId");

                    b.HasIndex("CptCode");

                    b.HasIndex("IcdCode");

                    b.ToTable("AuthorizationService");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Cptcode", b =>
                {
                    b.Property<string>("CptCode1")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cpt_code");

                    b.Property<string>("CptDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("cpt_description");

                    b.HasKey("CptCode1")
                        .HasName("PK__CPTCode__6E3A1E26574C30E4");

                    b.ToTable("CPTCode");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("department_name");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("facility_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__C2232422F8509D03");

                    b.HasIndex("FacilityId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Encounter", b =>
                {
                    b.Property<int>("EncounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("encounter_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EncounterId"));

                    b.Property<byte>("ConditionType")
                        .HasColumnType("tinyint")
                        .HasColumnName("condition_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<bool>("DoctorNotesVerified")
                        .HasColumnType("bit")
                        .HasColumnName("doctor_notes_verified");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("facility_id");

                    b.Property<bool>("IdentificationVerified")
                        .HasColumnType("bit")
                        .HasColumnName("identification_verified");

                    b.Property<bool>("InsuranceCardVerified")
                        .HasColumnType("bit")
                        .HasColumnName("insurance_card_verified");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<bool>("PrescriptionVerified")
                        .HasColumnType("bit")
                        .HasColumnName("prescription_verified");

                    b.Property<string>("Remarks")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("remarks");

                    b.Property<byte>("RequestStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("request_status");

                    b.Property<bool>("ScanVerified")
                        .HasColumnType("bit")
                        .HasColumnName("scan_verified");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<byte>("VerificationStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("verification_status");

                    b.HasKey("EncounterId")
                        .HasName("PK__Encounte__CDF1340F4DBFBBDF");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("PatientId");

                    b.ToTable("Encounter");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("facility_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FacilityLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("facility_location");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("facility_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.HasKey("FacilityId")
                        .HasName("PK__Facility__B2E8EAAE76796622");

                    b.ToTable("Facility");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Icdcode", b =>
                {
                    b.Property<string>("IcdCode1")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("icd_code");

                    b.Property<string>("IcdDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("icd_description");

                    b.HasKey("IcdCode1")
                        .HasName("PK__ICDCode__C282037F613EE440");

                    b.ToTable("ICDCode");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gender");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("identification_number");

                    b.Property<string>("IdentificationType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("identification_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("MrnNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mrn_number");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("PatientId")
                        .HasName("PK__Patient__4D5CE47646BA95FE");

                    b.HasIndex(new[] { "MrnNumber" }, "UQ__Patient__627085A816650500")
                        .IsUnique();

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Payer", b =>
                {
                    b.Property<int>("PayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayerId"));

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<byte>("NormalTatDays")
                        .HasColumnType("tinyint")
                        .HasColumnName("normal_tat_days");

                    b.Property<string>("PayerEmail")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("payer_email");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("payer_name");

                    b.Property<byte>("UrgentTatDays")
                        .HasColumnType("tinyint")
                        .HasColumnName("urgent_tat_days");

                    b.HasKey("PayerId")
                        .HasName("PK__Payer__9BC9732B89B14B98");

                    b.ToTable("Payer");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("patient_id");

                    b.Property<int>("PayerId")
                        .HasColumnType("int")
                        .HasColumnName("payer_id");

                    b.Property<DateOnly>("PolicyExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("policy_expiry_date");

                    b.Property<DateOnly>("PolicyStartDate")
                        .HasColumnType("date")
                        .HasColumnName("policy_start_date");

                    b.HasKey("PolicyId")
                        .HasName("PK__Policy__47DA3F03BC80E982");

                    b.HasIndex("PatientId");

                    b.HasIndex("PayerId");

                    b.ToTable("Policy");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Reminder", b =>
                {
                    b.Property<int>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reminder_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReminderId"));

                    b.Property<int>("AuthId")
                        .HasColumnType("int")
                        .HasColumnName("auth_id");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<int>("PayerId")
                        .HasColumnType("int")
                        .HasColumnName("payer_id");

                    b.Property<string>("Remarks")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("remarks");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_at");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("ReminderId")
                        .HasName("PK__Reminder__E27A36289F2976AD");

                    b.HasIndex("AuthId");

                    b.HasIndex("PayerId");

                    b.ToTable("Reminder");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.AuditHistory", b =>
                {
                    b.HasOne("PriorAuthorization.Shared.Entities.AuthorizationRequest", "Auth")
                        .WithMany("AuditHistories")
                        .HasForeignKey("AuthId")
                        .HasConstraintName("FK_AuditHistory_Auth");

                    b.HasOne("PriorAuthorization.Shared.Entities.Encounter", "Encounter")
                        .WithMany("AuditHistories")
                        .HasForeignKey("EncounterId")
                        .HasConstraintName("FK_AuditHistory_Encounter");

                    b.Navigation("Auth");

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.AuthorizationRequest", b =>
                {
                    b.HasOne("PriorAuthorization.Shared.Entities.Encounter", "Encounter")
                        .WithOne("AuthorizationRequest")
                        .HasForeignKey("PriorAuthorization.Shared.Entities.AuthorizationRequest", "EncounterId")
                        .IsRequired()
                        .HasConstraintName("FK_AuthorizationRequest_Encounter");

                    b.HasOne("PriorAuthorization.Shared.Entities.Payer", "Payer")
                        .WithMany("AuthorizationRequests")
                        .HasForeignKey("PayerId")
                        .IsRequired()
                        .HasConstraintName("FK_AuthorizationRequest_Payer");

                    b.Navigation("Encounter");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.AuthorizationService", b =>
                {
                    b.HasOne("PriorAuthorization.Shared.Entities.AuthorizationRequest", "Auth")
                        .WithMany("AuthorizationServices")
                        .HasForeignKey("AuthId")
                        .IsRequired()
                        .HasConstraintName("FK_AuthorizationService_Auth");

                    b.HasOne("PriorAuthorization.Shared.Entities.Cptcode", "CptCodeNavigation")
                        .WithMany("AuthorizationServices")
                        .HasForeignKey("CptCode")
                        .IsRequired()
                        .HasConstraintName("FK_AuthorizationService_CPT");

                    b.HasOne("PriorAuthorization.Shared.Entities.Icdcode", "IcdCodeNavigation")
                        .WithMany("AuthorizationServices")
                        .HasForeignKey("IcdCode")
                        .IsRequired()
                        .HasConstraintName("FK_AuthorizationService_ICD");

                    b.Navigation("Auth");

                    b.Navigation("CptCodeNavigation");

                    b.Navigation("IcdCodeNavigation");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Department", b =>
                {
                    b.HasOne("PriorAuthorization.Shared.Entities.Facility", "Facility")
                        .WithMany("Departments")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Department_Facility");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Encounter", b =>
                {
                    b.HasOne("PriorAuthorization.Shared.Entities.Department", "Department")
                        .WithMany("Encounters")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Encounter_Department");

                    b.HasOne("PriorAuthorization.Shared.Entities.Facility", "Facility")
                        .WithMany("Encounters")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Encounter_Facility");

                    b.HasOne("PriorAuthorization.Shared.Entities.Patient", "Patient")
                        .WithMany("Encounters")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Encounter_Patient");

                    b.Navigation("Department");

                    b.Navigation("Facility");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Policy", b =>
                {
                    b.HasOne("PriorAuthorization.Shared.Entities.Patient", "Patient")
                        .WithMany("Policies")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Policy_Patient");

                    b.HasOne("PriorAuthorization.Shared.Entities.Payer", "Payer")
                        .WithMany("Policies")
                        .HasForeignKey("PayerId")
                        .IsRequired()
                        .HasConstraintName("FK_Policy_Payer");

                    b.Navigation("Patient");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Reminder", b =>
                {
                    b.HasOne("PriorAuthorization.Shared.Entities.AuthorizationRequest", "Auth")
                        .WithMany("Reminders")
                        .HasForeignKey("AuthId")
                        .IsRequired()
                        .HasConstraintName("FK_Reminder_Auth");

                    b.HasOne("PriorAuthorization.Shared.Entities.Payer", "Payer")
                        .WithMany("Reminders")
                        .HasForeignKey("PayerId")
                        .IsRequired()
                        .HasConstraintName("FK_Reminder_Payer");

                    b.Navigation("Auth");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.AuthorizationRequest", b =>
                {
                    b.Navigation("AuditHistories");

                    b.Navigation("AuthorizationServices");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Cptcode", b =>
                {
                    b.Navigation("AuthorizationServices");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Department", b =>
                {
                    b.Navigation("Encounters");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Encounter", b =>
                {
                    b.Navigation("AuditHistories");

                    b.Navigation("AuthorizationRequest");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Facility", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Encounters");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Icdcode", b =>
                {
                    b.Navigation("AuthorizationServices");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Patient", b =>
                {
                    b.Navigation("Encounters");

                    b.Navigation("Policies");
                });

            modelBuilder.Entity("PriorAuthorization.Shared.Entities.Payer", b =>
                {
                    b.Navigation("AuthorizationRequests");

                    b.Navigation("Policies");

                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
